# Generated by Django 3.2 on 2023-05-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230511_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='won_prize_name',
        ),
    ]
